id: http://w3id.org/ontogpt/environmental-metadata
name: environmental-metadata
title: Environmental sample metadata
description: >-
  A template for categorizing Environmental Data Initiative
  data entries. See https://github.com/EDIorg/EDIorg-repository-index
license: https://creativecommons.org/publicdomain/zero/1.0/
prefixes:
  linkml: https://w3id.org/linkml/
  envmd: http://w3id.org/ontogpt/environmental-metadata

default_prefix: sample
default_range: string

imports:
  - linkml:types
  - core

classes:
  Dataset:
    tree_root: true
    attributes:
      packageid:
        description: The internal identifier for the dataset
        annotations:
          prompt: single unique identifier for the dataset
        range: string
        multivalued: false

      environmental_material:
        description: the environmental material that was sampled
        annotations:
          prompt: semicolon-separated list of environmental materials
        range: EnvironmentalMaterial
        multivalued: true

      environments:
        annotations:
          prompt: semicolon-separated list of environmental contexts in which the study was conducted
        multivalued: true
        range: Environment

  Location:
    is_a: NamedEntity
    id_prefixes:
      - ENVO
      - GAZ
    annotations:
      annotators: sqlite:obo:envo, bioportal:gaz

  EnvironmentalMaterial:
    is_a: NamedEntity
    id_prefixes:
      - ENVO
    annotations:
      annotators: sqlite:obo:envo

  Environment:
    is_a: NamedEntity
    id_prefixes:
      - ENVO
    annotations:
      annotators: sqlite:obo:envo

  Variable:
    is_a: NamedEntity
    id_prefixes:
      - ENVO
    annotations:
      annotators: sqlite:obo:envo
